### ISSUE TITLE
middlebury test

### ISSUE THREAD

**Issue by javierBarandiaran** [David-Zhao-1997/High-frequency-Stereo-Matching-Network#1]
Hi,
I am testing the  DLNR_SceneFlow.pth weights with the middlebury dataset, is this valid?. I am getting small values in the flow_pr disparity map.
I am using this parameters for evaluate_stereo.py:
--restore_ckpt DLNR_SceneFlow.pth --dataset middlebury_F --corr_implementation reg_cuda --mixed_precision
Thanks

**Comment by David-Zhao-1997** [comment]
Thank you for pointing out the problem. 

We have changed the names of some classes and functions in the process of making the code open source to make them as consistent as possible with the paper. However, instead of retraining the model, we edited the names in the checkpoints in order to keep the experimental results consistent with the paper. Due to some errors, we did not store the checkpoints correctly, we reworked the code and stored the checkpoints, please check the new checkpoint file in Release. 

If you have other questions and suggestions about checkpoints, feel free to mention them.

**Comment by javierBarandiaran** [comment]
Thank you very much

**Comment by javierBarandiaran** [comment]
Could you please give me the correct execution parameters to reproduce the Middlebury results?
I have tried with these parameters but the result is worse
--restore_ckpt DLNR_SceneFlow.pth --dataset middlebury_F --corr_implementation reg_cuda --valid_iters 32 
![image](https://github.com/David-Zhao-1997/High-frequency-Stereo-Matching-Network/assets/4264732/1f963c61-f7a5-4fe2-bb24-ce22bc554350)

**Comment by David-Zhao-1997** [comment]
If you want to reproduce the results of the Middlebury, you can use the Middlebury checkpoints we provide, you can find it in Release.

Since the scenes of Scene Flow dataset are different from the real-world scenes of Middlebury, we performed finetune, the process of finetne can refer to our paper.

**Comment by javierBarandiaran** [comment]
great! Thank you very much
