### ISSUE TITLE
Hidden states netC and net_h is shallowly copied during the update process

### ISSUE THREAD

**Issue by ZhxJia** [David-Zhao-1997/High-frequency-Stereo-Matching-Network#16]
https://github.com/David-Zhao-1997/High-frequency-Stereo-Matching-Network/blob/c10475fe30ff198781ecc7c712c24c781ff05096/core/dlnr.py#L101

Are the two hidden states always equal during the update process? It seems that these two variables are shared memory.

**Comment by David-Zhao-1997** [comment]
The issue does exist, but during the computation of LSTM, the update paths for C and H are different, so this approach is still effective. However, their values will be the same after each iteration (due to memory sharing). You can try using deep copy to completely separate these two variables, and it will boost the performance. If you conduct experiments at 1/8 resolution. The SceneFlow D1 error will drop from 6.68 to 6.50.
